config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles

  get 'js_articles' => "articles#js_articles"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      redirect_to "/"
    end
  end

  def index
    @articles = Article.all
  end

  def js_articles
    @js_articles = Article.all
    respond_to do |format|
      format.html
      format.json { render :json => @js_articles }
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      redirect_to "/"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path
    else
      redirect_to "/"
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    render_options = {
      # will remove from the output HTML tags inputted by user 
      filter_html:     false,
      # will insert <br /> tags in paragraphs where are newlines 
      # (ignored by default)
      hard_wrap:       true, 
      # hash for extra link options, for example 'nofollow'
      link_attributes: { rel: 'nofollow' }
      # more
      # will remove <img> tags from output
      # no_images: true
      # will remove <a> tags from output
      # no_links: true
      # will remove <style> tags from output
      # no_styles: true
      # generate links for only safe protocols
      # safe_links_only: true
      # and more ... (prettify, with_toc_data, xhtml)
    }
    renderer = Redcarpet::Render::HTML.new(render_options)

    extensions = {
      #will parse links without need of enclosing them
      autolink:           true,
      # blocks delimited with 3 ` or ~ will be considered as code block. 
      # No need to indent.  You can provide language name too.
      # ```ruby
      # block of code
      # ```
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      # will ignore standard require for empty lines surrounding HTML blocks
      lax_spacing:        true,
      lax_html_blocks: true,
      # will not generate emphasis inside of words, for example no_emph_no
      no_intra_emphasis:  true,
      # will parse strikethrough from ~~, for example: ~~bad~~
      strikethrough:      true,
      # will parse superscript after ^, you can wrap superscript in () 
      superscript:        true
      # will require a space after # in defining headers
      # space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_content_markdown(text)
    markdown(text.content)
  end

  def articles_content_md_truncated(a)
    truncate(articles_content_markdown(a), length: 80, separator: ' ', omission: '... ', :escape => false)
  end
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "btn btn-primary"

app/views/articles/edit.html.haml
%row
  .col-md-9
    %h1 
      New Article
      = link_to 'Back to home', articles_path, class:'btn btn-info'

%row
  .col-md-9
    = render 'form'

app/views/articles/index.html.haml
%row
  .col-md-9
    %h1 
      Articles
      = link_to 'New article', new_article_path, class:'btn btn-primary'
      = link_to 'Interactive articles', js_articles_path, {"class":"btn btn-warning", "data-toggle":"tooltip", "title":"'Read more' feature with vanillaJs!"}

    %hr

%row
  .col-md-9
    - @articles.each do |article|
      .col-xs-12
        %h2
          = article.title
        %h5 
          = article.created_at.strftime('%b %d, %Y')

        %section
          = articles_content_md_truncated(article)

        = link_to 'Read more', article_path(article) , class:'btn btn-info'
        = link_to 'Delete',  article,  method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"

      %hr

app/views/articles/js_articles.html.haml
%row
  .col-md-9
    %h1 
      Articles
      = link_to 'Back to home', articles_path, class:'btn btn-primary'

%row
  .col-md-9
    %h2
      "Read more" feature with vanillaJS

    %row
      .col-md-9
        %section(ng-repeat="article in articles")
          .articles(id="article-{{article.id}}")
            %h2
              {{article.title}}
            %p.ellipsis{"ng-bind-html": "article.content | markdown"}
            

            %a.btn.btn-success.more(href=""){"ng-click":"readMore()"}
              Read More

          %hr

app/views/articles/new.html.haml
%row
  .col-md-9
    %h1 
      New Article
      = link_to 'Back to home', articles_path, class:'btn btn-info'
%row
  .col-md-9
    = render 'form'

app/views/articles/show.html.haml
%row
  .col-md-9
    %h1 
      = @article.title
      = link_to 'Edit', edit_article_path(@article) ,  class:'btn btn-info'
      = link_to 'Back to home', articles_path, class:'btn btn-info'
%row
  .col-md-9
    %p
      %b Titre:
      = @article.title
    %p
      %b Texte:
      = articles_content_markdown(@article)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BlogFt
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/0.3.1/showdown.min.js'
    = javascript_include_tag 'https://code.angularjs.org/1.6.1/angular-sanitize.min.js'
  %body
    .container(ng-controller="articlesController")
      = yield